### ISSUE TITLE
Fix + Update Stealth Ability [ 60$ ]

### ISSUE THREAD

**Issue by c12hz** [TheSeekerGame/TheSeeker#118]
Currently there are 2 small problems with Stealth:
- stealth gets removed when you start attacking > it should only be removed when you successfully hit an enemy (I didn't make it clear previously my bad)
- stealth healing works strange, seems like you keep getting healed when attacking for some time after stealth? 

Here's the original overview of how stealth should work:
If the player ends the stealth by attacking that attack does double damage the player recovers 20% of max health.
If the player ends the stealth by attacking AND that attack also happens to be a critical hit the critical damage will get doubled and the stealth skill cooldown as well as all the other active cooldowns of other skills will get automatically reset to 0 and the player recovers 100% of max health.

So the healing in both instances is just a singular event, either the player recovers 20% health instantly or they recover 100% instantly

Also, it would be nice to make the damage number dealt with stealth be purple color, and if it's a stealth + critical maybe some brighter purple

**Comment by odecay** [comment]
Ill take this, I already had to rewrite stealth so I can make it behave correctly,

**Comment by odecay** [comment]
Do you want the lifesteal to be per instance of damage or only once per attack? Based on your description it seems like you'd prefer once per attack (on the first hit).
