### ISSUE TITLE
Damage Numbers over Enemies

### ISSUE THREAD

**Issue by c12hz** [TheSeekerGame/TheSeeker#36]
Damage numbers appearing above enemies once they receive damage.
Similar to games like Diablo or Risk of Rain:
https://www.youtube.com/watch?v=hIbK7SVi_0M

As far as I understand these numbers spawn above creatures at random horizontal offsets (so they don't all bunch up together too much), and then they float up slightly before disappearing.

**Comment by destravous** [comment]
https://github.com/TheSeekerGame/TheSeeker/pull/44
