### ISSUE TITLE
UI: Player Skill Toolbar with Icons

### ISSUE THREAD

**Issue by inodentry** [TheSeekerGame/TheSeeker#38]

**Comment by c12hz** [comment]
I added some documentation about how cooldowns/energy should work for these skills.
In terms of the visual look, I'm attaching an example.

![Image](https://github.com/TheSeekerGame/TheSeeker/assets/118369714/b30e0710-6674-4d94-bfda-db3e79164f38)

**Comment by c12hz** [comment]
oh, maybe I didn't make it clear on the example, all these skills are replaceable with any available skills the player wants.
Some can be cooldown based, some energy based, any kind can go into any of these 4 slots
