### ISSUE TITLE
Background Blur Shader

### ISSUE THREAD

**Issue by c12hz** [TheSeekerGame/TheSeeker#45]
A blur effect that's applied on all background layers, with the option to adjust the blur intensity.
The blur should be full resolution, without pixelation.

I've been going back and forth on whether we need this or not, but ultimately I'd like to test it in game to make a good decision.

I think the background blur could vastly increase the perception of depth in the game, and improve readability of the player and enemies a lot.

If we end up using the blur I think we could even  get rid of the background fog layers (they won't be very noticeable with the blur), and leave the fog in the foreground only.
Could help with performance too.

I'm attaching a very rough test I made in some photo editor.

![Image](https://github.com/TheSeekerGame/TheSeeker/assets/118369714/9c6149de-ee7f-4baf-8e9f-9c6c2ceff7f5)

**Comment by destravous** [comment]
Wip at: https://github.com/TheSeekerGame/TheSeeker/pull/73
currently blocked by tilemap work.
