### ISSUE TITLE
Projectile Movement and collision

### ISSUE THREAD

**Issue by c12hz** [TheSeekerGame/TheSeeker#50]
Projectile should arc/be entirely physics driven. (no homing affects)
When launched, enemy should do a few ray-casts first to try to avoid colliding with the ceiling.

**Comment by c12hz** [comment]
this is a good reference for particle movement/speed:
https://www.youtube.com/watch?v=4VqXMLL1tUE

**Comment by destravous** [comment]
pr: https://github.com/TheSeekerGame/TheSeeker/pull/56
