### ISSUE TITLE
Projectile particles

### ISSUE THREAD

**Issue by c12hz** [TheSeekerGame/TheSeeker#55]
a basic icy looking blob projectile made out of particles, or some combination of asset+particles.

I'm attaching a reference + some explanation

![Image](https://github.com/TheSeekerGame/TheSeeker/assets/118369714/f218fa67-c522-4599-b311-6b040f79348e)

**Comment by destravous** [comment]
Wip at: https://github.com/TheSeekerGame/TheSeeker/pull/57
