### ISSUE TITLE
Focus

### ISSUE THREAD

**Issue by c12hz** [TheSeekerGame/TheSeeker#61]
This is an ability that is instantaneous and doesn't have any visual component (we might add some particle effect later)
It simply makes your next damage deal 2x damage.
Then it goes on a 10second cooldown.
But, if the 2x damage hit is also a critical hit, then there's no cooldown.

For this to function we'll need critical hits in game.
For now we can add it to the 3rd variant of the sword slash animation.
I made this variant trigger on every 17th and 19th hit.
(Critical damage should deal 50% more damage and the damage captions should have a yellow color instead of white.)

So what this means is if you manage to count the amounts of hits correctly you can use this Focus ability right before you're about to deal critical damage, and then deal double crit damage and get 0 cooldown so you can keep using it for every crit if you're really good.

**Comment by destravous** [comment]
Adding some additional things mentioned on the discord:
> The main thing I care about is that when you hits a group of 5 enemies with a single damage source it will only count as 1 hit for the crit counter.
> And then once you get the crit all targets affected by the attack do get this crit

> for the critical hits, I’m thinking let’s not make it tied to any animation but instead just make them trigger on every 17th and 19th hit.
What I mean by hit is any frame with the pink dots counts as a hit no matter if you hit a target or not
